repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace

    - repo: https://github.com/python-poetry/poetry
      rev: "1.8"
      hooks:
          - id: poetry-check
          - id: poetry-lock

    - repo: https://github.com/PyCQA/flake8.git
      rev: "7.1.1"
      hooks:
          - id: flake8

    - repo: https://github.com/psf/black.git
      rev: "24.10.0"
      hooks:
          - id: black
