name: CI
on:
  # Only run on PR or main branch.
  # Prevent duplicate actions to safe compute time.
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        netbox-version:
          - v3.3.2
          - v3.4.4
          - v3.5.3
          - v3.6.7
          - v3.7.8
          - v4.0.2
          - latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Cache Poetry virtualenv
        uses: actions/cache@v4
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-$
          restore-keys: |
            poetry-$

      - name: Install Dependencies using Poetry
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Build test images
        run: |
          poetry run invoke build
        env:
          NETBOX_VER: ${{ matrix.netbox-version }}

      - name: Run tests
        run: |
          poetry run invoke tests
        env:
          NETBOX_VER: ${{ matrix.netbox-version }}
